<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findContenusRecents()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
        $qb->orderBy('c.datePublication', "DESC");
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }

    public function findContenusAussiConsultes($criteres)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
        $qb->join('c.conteneurs', 'conteneurs');
        $qb->where('c.conteneurs.annee=:critereAnnee');
        $qb->andWhere('c.conteneurs.groupe=:critereGroupe');
        $qb->andWhere('c.conteneurs.niveau=:critereNiveau');
        $qb->setParameter('critereAnnee', $criteres["annee"]);
        $qb->setParameter('critereAnnee', $criteres["groupe"]);
        $qb->setParameter('critereAnnee', $criteres["niveau"]);
        $qb->orderBy('c.nombreVueTotal', "DESC");
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }

}
