<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContenusFavoris(User $user)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c',  'userContenus');
        $qb->join('c.userContenus', 'userContenus');
        $qb->orderBy('userContenus.nbreVue', "DESC");
        $qb->setParameter('user', $user);
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
}
