<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ConteneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConteneurRepository extends \Doctrine\ORM\EntityRepository
{
    // Les contenus aussi consultés sont classés par ceux qui ont le plus grand nombre de vue totale
    public function findContenusAussiConsultes($criteres)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
        $qb->join('c.contenu', 'contenu');
        $qb->where('c.annee=:critereAnnee');
        $qb->setParameter('critereAnnee', $criteres["annee"]);
        $qb->orderBy('contenu.nombreVueTotal', "DESC");
        $qb->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
}