<?php

namespace AppBundle\Repository;

/**
 * ConteneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConteneurRepository extends \Doctrine\ORM\EntityRepository
{
}
