<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuRepository extends \Doctrine\ORM\EntityRepository
{


}
