<?php

namespace AppBundle\Repository;

/**
 * EnseignantGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
