<?php

namespace AppBundle\Repository;

/**
 * EnseignantContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantContenuRepository extends \Doctrine\ORM\EntityRepository
{
}
