<?php

namespace AppBundle\Repository;

/**
 * EnseignantGroupePromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantGroupePromotionRepository extends \Doctrine\ORM\EntityRepository
{
}
