<?php

namespace AppBundle\Repository;

/**
 * EtudiantContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantContenuRepository extends \Doctrine\ORM\EntityRepository
{
}
