<?php

namespace AppBundle\Repository;

/**
 * EtudiantGroupePromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantGroupePromotionRepository extends \Doctrine\ORM\EntityRepository
{
}
