<?php

namespace AppBundle\Repository;

/**
 * GroupeRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
