<?php

namespace AppBundle\Repository;

/**
 * PromotionNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
