<?php

namespace AppBundle\Repository;

/**
 * RubriqueSousRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueSousRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
