<?php

namespace AppBundle\Repository;

/**
 * RubriqueGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
