<?php

namespace AppBundle\Repository;

/**
 * SousRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
