<?php

namespace AppBundle\Repository;

/**
 * typeQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
