<?php

namespace AppBundle\Repository;

/**
 * UserContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserContributionRepository extends \Doctrine\ORM\EntityRepository
{
}
