<?php

namespace AppBundle\Repository;

/**
 * UserContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserContenuRepository extends \Doctrine\ORM\EntityRepository
{
}
