<?php

namespace AppBundle\Repository;

/**
 * UserReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
