<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function findUserOnlyWithCredentials($id)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u.id', 'u.nom', 'u.prenom', 'u.email','u.isBDE' , 'u.isPersonnel');
        $qb->where('u.id=:id');
        $qb->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

}
