<?php

namespace AppBundle\Repository;

/**
 * UserCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
