<?php

namespace AppBundle\Repository;

/**
 * UserGroupePromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupePromotionRepository extends \Doctrine\ORM\EntityRepository
{
}
