<?php

namespace AppBundle\Repository;

/**
 * VisiteContenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteContenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastVisiteContenuByDate($user, $contenu)
    {
        $qb = $this->createQueryBuilder('vc');;
        $qb->select("vc.id, MAX(vc.dateVisite) as dateMax");
        $qb->where("vc.user=:user");
        $qb->andWhere('vc.contenu = :contenu');
        $qb->setParameter('user', $user);
        $qb->setParameter('contenu', $contenu);
        $qb->orderBy('vc.dateVisite' , "DESC");
        return $qb->getQuery()->getSingleResult();
    }

    public function findAllVisiteContenuByDate($contenu)
    {
        $qb = $this->createQueryBuilder('vc');;
        $qb->select("vc.id, DATE_FORMAT(vc.dateVisite, '%Y%m%d') , SUM(vc.duree)");
        $qb->groupBy("DATE_FORMAT(vc.dateVisite, '%Y%m%d')");
        $qb->where('vc.contenu = :contenu');
        $qb->setParameter('contenu', $contenu);
        $qb->orderBy('vc.dateVisite' , "ASC");
        return $qb->getQuery()->getResult();
    }
}
