<?php

namespace AppBundle\Repository;


/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNoteEtudiant($userID)
    {
        $qb = $this->createQueryBuilder('v');;
        $qb->select("v.valeur", "v.dateVote");
        $qb->where("v.ref=:ref");
        $qb->andWhere('v.userID = :userID');
        $qb->setParameter('ref', 'Contenu');
        $qb->setParameter('userID', $userID);
        $qb->orderBy('contenu.datePublication' , "DESC");

        return $qb->getQuery()->getResult();
    }
}
