app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UserController

lectureContenu:
    type:     rest
    resource: AppBundle\Controller\ContenuController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController