AppBundle\Entity\Contenu:
    attributes:
        id:
            groups: ['contenu', 'question',  'userContenu', 'visiteContenu', 'rubrique', 'conteneur']
        titre:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        description:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        datePublication:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        note:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        nombreVueTotal:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        contenuRoot:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        imageRoot:
            groups: ['contenu', 'question',  'userContenu', 'rubrique', 'conteneur']
        rubrique:
            groups: ['contenu', 'question',  'userContenu']
        sousRubrique:
            groups: ['contenu', 'question',  'userContenu']
        questions:
            groups: ['contenu']
        userContenus:
            groups: ['contenu']


AppBundle\Entity\Question:
    attributes:
        id:
            groups: ['contenu', 'question', 'reponse',  'user']
        libelle:
            groups: ['contenu', 'question', 'reponse',  'user']
        description:
            groups: ['contenu', 'question', 'reponse',  'user']
        datePublication:
            groups: ['contenu', 'question', 'reponse',  'user']
        nombreLike:
            groups: ['contenu', 'question', 'reponse',  'user']
        nombreVu:
            groups: ['contenu', 'question', 'reponse',  'user']
        page:
            groups: ['contenu', 'question', 'reponse',  'user']
        ligne:
            groups: ['contenu', 'question', 'reponse',  'user']
        nbreInutile:
            groups: ['contenu', 'question', 'reponse',  'user']
        anonyme:
            groups: ['contenu', 'question', 'reponse',  'user']
        hasVoted:
            groups: ['contenu', 'question', 'reponse',  'user']
        user:
            groups: ['question', 'reponse', 'user']
        typeQuestion:
            groups: ['question', 'reponse',  'user']
        reponses:
            groups: ['question']

AppBundle\Entity\TypeQuestion:
    attributes:
        id:
            groups: ['typeQuestion', 'question']
        libelle:
            groups: ['typeQuestion', 'question']


AppBundle\Entity\UserContenu:
    attributes:
        id:
            groups: ['contenu', 'userContenu']
        nbreVue:
            groups: ['contenu', 'userContenu']
        aPublie:
            groups: ['contenu', 'userContenu']
        review:
            groups: ['contenu', 'userContenu']
        user:
            groups: ['contenu', 'userContenu']
        contenu:
            groups: ['userContenu']


AppBundle\Entity\Reponse:
    attributes:
        id:
            groups: ['reponse', 'commentaire',  'user', 'question']
        libelle:
            groups: ['reponse', 'commentaire',  'user', 'question']
        typeReponse:
            groups: ['reponse', 'commentaire',  'user', 'question']
        datePublication:
            groups: ['reponse', 'commentaire',  'user', 'question']
        nombreLike:
            groups: ['reponse', 'commentaire',  'user', 'question']
        nbreInutile:
            groups: ['reponse', 'commentaire',  'user', 'question']
        anonyme:
            groups: ['reponse', 'commentaire',  'user', 'question']
        hasVoted:
            groups: ['reponse', 'commentaire',  'user', 'question']
        user:
            groups: ['reponse', 'question']
        question:
            groups: ['commentaire']
        commentaires:
            groups: ['reponse', 'question']


AppBundle\Entity\Commentaire:
    attributes:
        id:
            groups: ['reponse', 'commentaire',  'user', 'question']
        libelle:
            groups: ['reponse', 'commentaire',  'user', 'question']
        parent_id:
            groups: ['reponse', 'commentaire',  'user', 'question']
        datePublication:
            groups: ['reponse', 'commentaire',  'user', 'question']
        depth:
            groups: ['reponse', 'commentaire',  'user', 'question']
        nombreLike:
            groups: ['reponse', 'commentaire',  'user', 'question']
        nbreInutile:
            groups: ['reponse', 'commentaire',  'user', 'question']
        anonyme:
            groups: ['reponse', 'commentaire',  'user', 'question']
        hasVoted:
            groups: ['reponse', 'commentaire',  'user', 'question']
        user:
            groups: ['reponse', 'commentaire', 'question']
        reponse:
            groups: ['commentaire']



AppBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        email:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        nom:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        prenom:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        userProfilRoot:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        dateCreation:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        isBDE:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']
        isPersonnel:
            groups: ['user', 'commentaire', 'question', 'reponse', 'auth-token']




#Serialisation for user homepage

AppBundle\Entity\Conteneur:
    attributes:
        id:
            groups: ['annee', 'groupe', 'niveau' , 'contenu', 'conteneur']
        annee:
            groups: ['conteneur']
        groupe:
            groups: ['conteneur']
        niveau:
            groups: ['conteneur']
        contenu:
            groups: ['conteneur']


AppBundle\Entity\Annee:
    attributes:
        id:
            groups: ['annee', 'conteneur']
        libelle:
            groups: ['annee', 'conteneur']
        conteneurs:
            groups: ['annee']

AppBundle\Entity\Groupe:
    attributes:
        id:
            groups: ['groupe', 'conteneur']
        libelle:
            groups: ['groupe', 'conteneur']
        conteneurs:
            groups: ['groupe']

AppBundle\Entity\Niveau:
    attributes:
        id:
            groups: ['niveau', 'conteneur']
        libelle:
            groups: ['niveau', 'conteneur']
        conteneurs:
            groups: ['niveau']

AppBundle\Entity\Rubrique:
    attributes:
        id:
            groups: ['rubrique', 'groupeRubrique', 'sousRubrique', 'contenu']
        libelle:
            groups: ['rubrique', 'groupeRubrique', 'sousRubrique', 'contenu']
        imageRoot:
            groups: ['rubrique', 'groupeRubrique', 'sousRubrique', 'contenu']
        presentation:
            groups: ['rubrique', 'groupeRubrique', 'sousRubrique', 'contenu']
        importance:
            groups: ['rubrique', 'groupeRubrique', 'sousRubrique', 'contenu']
#        groupeRubrique:
#            groups: ['rubrique']


AppBundle\Entity\GroupeRubrique:
    attributes:
        id:
            groups: ['groupeRubrique', 'rubrique']
        libelle:
            groups: ['groupeRubrique', 'rubrique']
        rubriques:
            groups: ['groupeRubrique']

AppBundle\Entity\SousRubrique:
    attributes:
        id:
            groups: ['sousRubrique', 'rubrique', 'contenu']
        libelle:
            groups: ['sousRubrique', 'rubrique', 'contenu']


AppBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']

AppBundle\Entity\Vote:
    attributes:
        id:
            groups: ['vote']
        userID:
            groups: ['vote']
        refID:
            groups: ['vote']
        ref:
            groups: ['vote']
        valeur:
            groups: ['vote']
        dateVote:
            groups: ['vote']

AppBundle\Entity\Image:
    attributes:
        id:
            groups: ['image']
        userID:
            groups: ['image']
        imageRoot:
            groups: ['image']
        dateUpload:
            groups: ['image']

AppBundle\Entity\VisiteContenu:
    attributes:
        id:
            groups: ['visiteContenu']
        dateVisite:
            groups: ['visiteContenu']
        duree:
            groups: ['visiteContenu']
        user:
            groups: ['visiteContenu']
        contenu:
            groups: ['visiteContenu']

AppBundle\Entity\PromotionNotification:
    attributes:
        id:
            groups: ['annee', 'groupe', 'niveau' , 'user', 'promotionNotification']
        annee:
            groups: ['promotionNotification']
        groupe:
            groups: ['promotionNotification']
        niveau:
            groups: ['promotionNotification']
        user:
            groups: ['promotionNotification']