AppBundle\Entity\Contenu:
    attributes:
        id:
            groups: ['contenu', 'question',  'userContenu']
        titre:
            groups: ['contenu', 'question',  'userContenu']
        information:
            groups: ['contenu', 'question',  'userContenu']
        datePublication:
            groups: ['contenu', 'question',  'userContenu']
        nombreLike:
            groups: ['contenu', 'question',  'userContenu']
        nombreVueTotal:
            groups: ['contenu', 'question',  'userContenu']
        contenuRoot:
            groups: ['contenu', 'question',  'userContenu']
        imageRoot:
            groups: ['contenu', 'question',  'userContenu']
        rubrique:
            groups: ['contenu', 'question',  'userContenu']
        questions:
            groups: ['contenu']
        userContenus:
            groups: ['contenu']


AppBundle\Entity\Question:
    attributes:
        id:
            groups: ['contenu', 'question', 'reponse',  'user']
        libelle:
            groups: ['contenu', 'question', 'reponse',  'user']
        description:
            groups: ['contenu', 'question', 'reponse',  'user']
        datePublication:
            groups: ['contenu', 'question', 'reponse',  'user']
        nombreLike:
            groups: ['contenu', 'question', 'reponse',  'user']
        nombreDislike:
            groups: ['contenu', 'question', 'reponse',  'user']
        page:
            groups: ['contenu', 'question', 'reponse',  'user']
        ligne:
            groups: ['contenu', 'question', 'reponse',  'user']
        imageRoot:
            groups: ['contenu', 'question', 'reponse',  'user']
        report:
            groups: ['contenu', 'question', 'reponse',  'user']
        typeQuestion:
            groups: ['contenu', 'question', 'reponse',  'user']
        users:
            groups: ['contenu', 'question']
        reponses:
            groups: ['contenu']









AppBundle\Entity\UserContenu:
    attributes:
        id:
            groups: ['contenu', 'userContenu']
        nbreVue:
            groups: ['contenu', 'userContenu']
        user:
            groups: ['contenu', 'userContenu']
        contenu:
            groups: ['userContenu']

AppBundle\Entity\Reponse:
    attributes:
        id:
            groups: ['reponse', 'commentaire',  'user']
        libelle:
            groups: ['reponse', 'commentaire',  'user']
        type:
            groups: ['reponse', 'commentaire',  'user']
        datePublication:
            groups: ['reponse', 'commentaire',  'user']
        nombreLike:
            groups: ['reponse', 'commentaire',  'user']
        report:
            groups: ['reponse', 'commentaire',  'user']
        question:
            groups: [ 'commentaire']
        commentaires:
            groups: ['reponse']

        users:
            groups: ['reponse']

AppBundle\Entity\Commentaire:
    attributes:
        id:
            groups: ['reponse', 'commentaire',  'user']
        libelle:
            groups: ['reponse', 'commentaire',  'user']
        parent_id:
            groups: ['reponse', 'commentaire',  'user']
        datePublication:
            groups: ['reponse', 'commentaire',  'user']
        depth:
            groups: ['reponse', 'commentaire',  'user']
        nombreLike:
            groups: ['reponse', 'commentaire',  'user']
        report:
            groups: ['reponse', 'commentaire',  'user']
        users:
            groups: ['reponse', 'commentaire']
        reponse:
            groups: ['commentaire']



AppBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'commentaire', 'question', 'reponse']
        email:
            groups: ['user', 'commentaire', 'question', 'reponse']
        nom:
            groups: ['user', 'commentaire', 'question', 'reponse']
        prenom:
            groups: ['user', 'commentaire', 'question', 'reponse']
        dateCreation:
            groups: ['user', 'commentaire', 'question', 'reponse']
        isBDE:
            groups: ['user', 'commentaire', 'question', 'reponse']
        isEnseignant:
            groups: ['user', 'commentaire', 'question', 'reponse']
        commentaires:
            groups: ['user']
        reponses:
            groups: [ 'user']
        questions:
            groups: ['user']

            
