AppBundle\Entity\Contenu:
    attributes:
        id:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        titre:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        information:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        datePublication:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        nombreLike:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        nombreVueTotal:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        contenuRoot:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        imageRoot:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        rubrique:
            groups: ['contenu', 'question', 'enseignantContenu', 'etudiantContenu']
        questions:
            groups: ['contenu']
        enseignantContenus:
            groups: ['contenu']
        etudiantContenus:
            groups: ['contenu']


AppBundle\Entity\Question:
    attributes:
        id:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        libelle:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        description:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        datePublication:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        nombreLike:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        nombreDislike:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        page:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        ligne:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        imageRoot:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        report:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        typeQuestion:
            groups: ['contenu', 'question', 'reponse', 'enseignant', 'etudiant']
        enseignants:
            groups: ['contenu', 'question']
        etudiants:
            groups: ['contenu', 'question']
        reponses:
            groups: ['contenu']




AppBundle\Entity\EnseignantContenu:
    attributes:
        id:
            groups: ['contenu', 'enseignantContenu']
        nbreVue:
            groups: ['contenu', 'enseignantContenu']
        enseignant:
            groups: ['contenu', 'enseignantContenu']
        contenu:
            groups: ['EnseignantContenu']

AppBundle\Entity\Enseignant:
    attributes:
        id:
            groups: ['contenu', 'enseignant']
        email:
            groups: ['contenu', 'enseignant']
        nom:
            groups: ['contenu', 'enseignant']
        prenom:
            groups: ['contenu', 'enseignant']
        contenu:
            groups: ['EnseignantContenu']


AppBundle\Entity\EtudiantContenu:
    attributes:
        id:
            groups: ['contenu', 'etudiantContenu']
        nbreVue:
            groups: ['contenu', 'etudiantContenu']
        etudiant:
            groups: ['contenu', 'etudiantContenu']
        contenu:
            groups: ['etudiantContenu']

AppBundle\Entity\Reponse:
    attributes:
        id:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        libelle:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        type:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        datePublication:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        nombreLike:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        report:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        question:
            groups: [ 'commentaire']
        commentaires:
            groups: ['reponse']
        enseignants:
            groups: ['reponse']
        etudiants:
            groups: ['reponse']

AppBundle\Entity\Commentaire:
    attributes:
        id:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        libelle:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        parent_id:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        datePublication:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        depth:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        nombreLike:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        report:
            groups: ['reponse', 'commentaire', 'enseignant', 'etudiant']
        enseignants:
            groups: ['reponse', 'commentaire']
        etudiants:
            groups: ['reponse', 'commentaire']
        reponse:
            groups: ['commentaire']


AppBundle\Entity\Enseignant:
    attributes:
        id:
            groups: ['enseignant', 'commentaire', 'question', 'reponse']
        email:
            groups: ['enseignant', 'commentaire', 'question', 'reponse']
        nom:
            groups: ['enseignant', 'commentaire', 'question', 'reponse']
        prenom:
            groups: ['enseignant', 'commentaire', 'question', 'reponse']
        dateCreation:
            groups: ['enseignant', 'commentaire', 'question', 'reponse']
        commentaires:
            groups: ['enseignant']
        reponses:
            groups: [ 'enseignant']
        questions:
            groups: ['enseignant']

AppBundle\Entity\Etudiant:
    attributes:
        id:
            groups: ['etudiant', 'commentaire', 'question', 'reponse']
        email:
            groups: ['etudiant', 'commentaire', 'question', 'reponse']
        nom:
            groups: ['etudiant', 'commentaire', 'question', 'reponse']
        prenom:
            groups: ['etudiant', 'commentaire', 'question', 'reponse']
        dateCreation:
            groups: ['etudiant', 'commentaire', 'question', 'reponse']
        membreBDE:
            groups: ['etudiant', 'commentaire', 'question', 'reponse']
        commentaires:
            groups: ['etudiant']
        reponses:
            groups: [ 'etudiant']
        questions:
            groups: ['etudiant']

            
