# src/AppBundle/Resources/config/validation.yml

AppBundle\Entity\Question:
    properties:
        libelle:
            - NotBlank: ~
            - Type: string
        description:
            - NotBlank: ~
            - Type: string
        page:
            - Type: integer
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 1000
        anonyme:
            - Type: bool
        ligne:
            - Type: integer
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 1000

AppBundle\Entity\Reponse:
    properties:
        libelle:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Commentaire:
    properties:
        libelle:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\User:
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 8
                max: 50
        gRecaptchaResponse:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
        croppedDataUrl:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
        picFileName:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string


AppBundle\Entity\Credentials:
    properties:
          login:
              - NotBlank: ~
              - Type: string
          password:
              - NotBlank: ~
              - Type: string


AppBundle\Entity\Contenu:
    properties:
          titre:
              - NotBlank: ~
              - Type: string
          description:
              - NotBlank: ~
              - Type: string
          imageRoot:
              - NotBlank: ~
              - Type: string
          contenuRoot:
              - NotBlank: ~
              - Type: string
#         note:
#              - Type: float
#              - GreaterThanOrEqual:
#                  value: 0
#              - LessThanOrEqual:
#                  value: 5

AppBundle\Entity\Vote:
    properties:
        valeur:
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 5

